### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by rubensworks** [comment]
Thanks!
The 1.12 version is not being maintained anymore though, and will not receive any more updates.
So feel free to submit another PR to the main 1.16 branch.

I'll merge this in any case, in case people would want to compile the mod themselves.

**Comment by Blueberryy** [comment]
1.12 is 1.12.2 right?

**Comment by rubensworks** [comment]
Yep

**Comment by Blueberryy** [comment]
Then please add my translation to it. I made translation because Universal
Bestiary supports your mod and i kinda like your mod :)

**Pull request merged**
